name: 'Branch Naming'

on:
  create:
    branches:

jobs:
  check_name:
    runs-on: ubuntu-latest
    steps:
      - name: Now checking the branch name
        run: |
          echo "Checking branch name: ${{ github.ref }}"
          if [[ "${{ github.ref }}" =~ ^refs\/heads\/Feature/.*|^refs\/heads\/Experiment/.*$  ]]; then
            echo "Branch name is acceptable"
          else
            echo "error: Branch name does not meet standard" >&2
            exit 1
          fi
